### PR TITLE
Update packages and node version

### PR DESCRIPTION
**Pull request by Teko012**
[Github is removing](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) the deprecated node12 from the latest runner. It has also changed the [output handling](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This PR should take care of both things, and it also fixes a change in behaviour that comes from the `@actions/core` package bump.

### CODE REVIEW

**Comment by Teko012** [comment]
@mavrosxristoforos What do you think of this fix? :)

**Comment by mavrosxristoforos** [comment]
@Teko012 Have you tested it and it works?

**Comment by Teko012** [comment]
@mavrosxristoforos For my usage, it worked, and it resulted in the same output with the fix. I have also tried the included `test.xml`. I haven't tried all the possible options, since I'm not so familiar with all the possibilities, so maybe worth a look for you as well.

**Comment by mavrosxristoforos** [comment]
Okay I tested the command line myself with the different options described in the readme file and it works. Merging...

**Comment by mavrosxristoforos** [comment]
Thank you for your contribution!

**Pull request merged**
