### PR TITLE
Update build method and node dependencies

### PR DESCRIPTION
**Pull request by Teko012**
The node modules were out of sync with the package file. There was also a package name change which resulted in being out of sync. To solve these, I've moved the build to use `ncc` (as [described it here](https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#commit-tag-and-push-your-action-to-github)), and updated the dependencies to the correct one.

I've tried to test it as best as I could, but please also test it.

### CODE REVIEW

**Comment by Teko012** [comment]
@mavrosxristoforos What do you think about this?

**Comment by mavrosxristoforos** [comment]
@Teko012 Thanks for your contributions!
I haven't had the time to review all your changes. Have you tested if it works with existing workflows or is this a breaking change?

**Comment by Teko012** [comment]
@mavrosxristoforos It shouldn't be a breaking change, it should result in the same output, it is just packaged differently (beside the dependency updates). I've tested a few scenarios, and they seemed to have worked, but it would be great if you also tested it when you have time.

**Comment by Teko012** [comment]
@mavrosxristoforos Have you had the chance to test it out?

**Comment by mavrosxristoforos** [comment]
I'm still trying to figure this out. I apologize. Time is very limited. Please help me understand. I see that you have updated the action.yml, but not the README.md on how to test this directly from the console. `node index.js -f test.xml -p //version` doesn't work, for example. So, does this only work when invoked as an action?

**Comment by Teko012** [comment]
@mavrosxristoforos No, you can run `dist/index.js` from the console if you want to test the built version.

**Comment by Teko012** [comment]
@mavrosxristoforos I updated the readme, sorry about the confusion.

**Comment by Teko012** [comment]
@mavrosxristoforos Have you had time to test this out?

**Comment by Teko012** [comment]
@mavrosxristoforos I updated the dependencies to the latest

**Comment by Teko012** [comment]
@mavrosxristoforos Updated them again

**Pull request merged**
