### PR TITLE
Make it work for string-typed xpath expressions

### PR DESCRIPTION
**Pull request by m-ringler**
Sorry. Old PR #19 got closed after I renamed my repo and branch.

> Hi @m-ringler and thank you for your contribution! Could you please also provide an example of your XML?

Sure, this is the full beauty
~~~xml
<Project>
	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<MSBuildCopyContentTransitively>True</MSBuildCopyContentTransitively>
		<Nullable>enable</Nullable>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)CodeAnalysis.ruleset</CodeAnalysisRuleSet>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>

		<!-- Version -->
		<VersionPrefix>1.0.0</VersionPrefix>
		<VersionSuffix>alpha.21</VersionSuffix>
	</PropertyGroup>
</Project>
~~~
Only the Version elements are relevant - so you can strip everything else if you are looking for a minimal repro case.
Evaluating the XPath expression concat(//VersionPrefix/text(), "-", //VersionSuffix/text()) against this document should produce the string 1.0.0-alpha.21. See e. g. https://www.freeformatter.com/xpath-tester.htm

### CODE REVIEW

**Comment by Teko012** [comment]
@m-ringler Can you bump the version as well in `package.json` (possibly the `@actions/core` dependency as well to the latest), and then include that in the PR along with the `package-lock.json` and the afterwards rebuilt `dist/index.js` as well? You can find information in the README on how to build it.

**Comment by m-ringler** [comment]
> @m-ringler Can you bump the version as well in `package.json` (possibly the `@actions/core` dependency as well to the latest), and then include that in the PR along with the `package-lock.json` and the afterwards rebuilt `dist/index.js` as well? You can find information in the README on how to build it.

Done

**Comment by Teko012** [comment]
@m-ringler I think you built it with the old version dependencies, so the new package versions were not used with the build. Can you install the new packages and then try to build it again?

**Comment by m-ringler** [comment]
> @m-ringler I think you built it with the old version dependencies, so the new package versions were not used with the build. Can you install the new packages and then try to build it again?

@Teko012 I have run npm install and rebuilt dist/index.js and git status says there's nothing to commit. I also checked that my local branch is in sync with the branch on github. So I don't get what you want me to do. Can you just give me the command line?

**Comment by Teko012** [comment]
@m-ringler An `rm -r node_modules` should solve it before running the other commands, but I rebuilt it again, and the change I saw is gone, so maybe it was something on my end. Sorry about it :)

**Comment by mavrosxristoforos** [comment]
So can you both confirm that this is ready to merge? Should I do something before merging?

**Comment by Teko012** [comment]
I think it should be good, but I haven't tested the specific use cases, only the "packaging".

**Comment by mavrosxristoforos** [comment]
Could you possibly test the cases written in the readme file?

**Comment by Teko012** [comment]
It still seems to work

**Comment by m-ringler** [comment]
Sorry, I felt obliged to contribute an upstream fix. But I have done what I could, here. Now it is up to you to merge or close the PR, I won't mind either way.

**Comment by mavrosxristoforos** [comment]
Don't worry, I'm sure you did your best.
I just want to test it a lit bit further.

**Pull request merged**
